// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for connections to Bitbucket Data Center.
public struct BitbucketDataCenterConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The URI of the Bitbucket Data Center instance or cluster this
  /// connection is for.
  public var hostUri: Swift.String = Swift.String()

  /// Required. Immutable. SecretManager resource containing the webhook secret
  /// used to verify webhook events, formatted as
  /// `projects/*/secrets/*/versions/*`.
  public var webhookSecretSecretVersion: Swift.String = Swift.String()

  /// Required. A http access token with the `REPO_READ` access.
  public var readAuthorizerCredential: UserCredential? = nil

  /// Required. A http access token with the `REPO_ADMIN` scope access.
  public var authorizerCredential: UserCredential? = nil

  /// Optional. Configuration for using Service Directory to privately connect to
  /// a Bitbucket Data Center. This should only be set if the Bitbucket Data
  /// Center is hosted on-premises and not reachable by public internet. If this
  /// field is left empty, calls to the Bitbucket Data Center will be made over
  /// the public internet.
  public var serviceDirectoryConfig: ServiceDirectoryConfig? = nil

  /// Optional. SSL certificate to use for requests to the Bitbucket Data Center.
  public var sslCa: Swift.String = Swift.String()

  /// Output only. Version of the Bitbucket Data Center running on the
  /// `host_uri`.
  public var serverVersion: Swift.String = Swift.String()

  /// Initialize a new instance of `BitbucketDataCenterConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BitbucketDataCenterConfig().with { $0.hostUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v2.BitbucketDataCenterConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
