// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A connection to a SCM like GitHub, GitHub Enterprise, Bitbucket Data Center,
/// Bitbucket Cloud or GitLab.
public struct Connection: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Immutable. The resource name of the connection, in the format
  /// `projects/{project}/locations/{location}/connections/{connection_id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Server assigned timestamp for when the connection was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Server assigned timestamp for when the connection was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Installation state of the Connection.
  public var installationState: InstallationState? = nil

  /// If disabled is set to true, functionality is disabled for this connection.
  /// Repository based API methods and webhooks processing for repositories in
  /// this connection will be disabled.
  public var disabled: Swift.Bool = Swift.Bool()

  /// Output only. Set to true when the connection is being set up or updated in
  /// the background.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Allows clients to store small amounts of arbitrary data.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// This checksum is computed by the server based on the value of other
  /// fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Configuration for the connection depending on the type of provider.
  public var connectionConfig: OneOf_ConnectionConfig? = nil

  /// Initialize a new instance of `Connection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Connection().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case githubConfig = "githubConfig"
    case githubEnterpriseConfig = "githubEnterpriseConfig"
    case gitlabConfig = "gitlabConfig"
    case bitbucketDataCenterConfig = "bitbucketDataCenterConfig"
    case bitbucketCloudConfig = "bitbucketCloudConfig"
    case installationState = "installationState"
    case disabled = "disabled"
    case reconciling = "reconciling"
    case annotations = "annotations"
    case etag = "etag"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.installationState = try container.decodeIfPresent(
      InstallationState.self, forKey: .installationState)
    self.disabled = try container.decode(Swift.Bool.self, forKey: .disabled)
    self.reconciling = try container.decode(Swift.Bool.self, forKey: .reconciling)
    self.annotations = try container.decode([Swift.String: Swift.String].self, forKey: .annotations)
    self.etag = try container.decode(Swift.String.self, forKey: .etag)

    var connectionConfig: OneOf_ConnectionConfig? = nil
    let connectionConfigCheckAndSet = {
      if connectionConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'connectionConfig'"))
      }
      connectionConfig = $0
    }
    if let githubConfig = try container.decodeIfPresent(GitHubConfig?.self, forKey: .githubConfig) {
      try connectionConfigCheckAndSet(.githubConfig(githubConfig))
    }
    if let githubEnterpriseConfig = try container.decodeIfPresent(
      GitHubEnterpriseConfig?.self, forKey: .githubEnterpriseConfig)
    {
      try connectionConfigCheckAndSet(.githubEnterpriseConfig(githubEnterpriseConfig))
    }
    if let gitlabConfig = try container.decodeIfPresent(GitLabConfig?.self, forKey: .gitlabConfig) {
      try connectionConfigCheckAndSet(.gitlabConfig(gitlabConfig))
    }
    if let bitbucketDataCenterConfig = try container.decodeIfPresent(
      BitbucketDataCenterConfig?.self, forKey: .bitbucketDataCenterConfig)
    {
      try connectionConfigCheckAndSet(.bitbucketDataCenterConfig(bitbucketDataCenterConfig))
    }
    if let bitbucketCloudConfig = try container.decodeIfPresent(
      BitbucketCloudConfig?.self, forKey: .bitbucketCloudConfig)
    {
      try connectionConfigCheckAndSet(.bitbucketCloudConfig(bitbucketCloudConfig))
    }
    self.connectionConfig = connectionConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.installationState, forKey: .installationState)
    try container.encode(self.disabled, forKey: .disabled)
    try container.encode(self.reconciling, forKey: .reconciling)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.etag, forKey: .etag)

    if let choice = self.connectionConfig {
      switch choice {
      case .githubConfig(let value):
        try container.encode(value, forKey: .githubConfig)
      case .githubEnterpriseConfig(let value):
        try container.encode(value, forKey: .githubEnterpriseConfig)
      case .gitlabConfig(let value):
        try container.encode(value, forKey: .gitlabConfig)
      case .bitbucketDataCenterConfig(let value):
        try container.encode(value, forKey: .bitbucketDataCenterConfig)
      case .bitbucketCloudConfig(let value):
        try container.encode(value, forKey: .bitbucketCloudConfig)
      }
    }
  }

  /// Configuration for the connection depending on the type of provider.
  public enum OneOf_ConnectionConfig: Codable, Equatable, Sendable {
    /// Configuration for connections to github.com.
    indirect case githubConfig(GitHubConfig?)
    /// Configuration for connections to an instance of GitHub Enterprise.
    indirect case githubEnterpriseConfig(GitHubEnterpriseConfig?)
    /// Configuration for connections to gitlab.com or an instance of GitLab
    /// Enterprise.
    indirect case gitlabConfig(GitLabConfig?)
    /// Configuration for connections to Bitbucket Data Center.
    indirect case bitbucketDataCenterConfig(BitbucketDataCenterConfig?)
    /// Configuration for connections to Bitbucket Cloud.
    indirect case bitbucketCloudConfig(BitbucketCloudConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v2.Connection"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
